export const BASE_URL = "http://51.20.168.126:5879/api/";
export const POST_METHOD = "POST";
export const GET_METHOD = 'GET';
export const PUTMETHOD ="PUT";
export const DELETE="DELETE";
export const IMAGEUPLOAD = "user/upload-image";
export const LOGIN= 'user/login';
export const REGISTER ="user/sign-up";
export const UPDATE_PROFESSIONAL_DETAILS= "user/update-professional-details";
export const GET_CLIENT ="rates/get-client";
export const GET_GROUP_LIST="group/getGroupList";
export const GET_PROFILE ="user/get-profile";
export const GET_CLIENT_DETAILS= 'rates/getClientDetails'
export const GET_RATES="rates/get-rates"
export const CREATE_OR_UPDATE_CLIENT= "rates/create-or-update-client"
export const GET_TRANNING_SESSION ="tranning/getTrainingSession"
export const CREATE_UPDATE_RATE = "rates/create-or-update-rates"
export const UPDATE_PROILE = "user/update-profile"
export const DELETE_RATES='rates/delete-rates'
export const DASHBOARD_DATA='user/getDashboardData?'